- name: Installing packages from loop
  hosts: localhost
  become: yes
  tasks:
   - name: Installing packages
     ansible.builtin.package:
       name: "{{item}}"
       state: present
     loop:
       - mysql
       - postfix
       - git