- name: variables from task level
  hosts: localhost
  tasks:
   - name: check variable
     vars:
      Course: DevOps
      Trainer: Nivas
      Duration: 110HRS
    ansible.builtin.debug:
      msg: " Hi I am learning, {{Course}} and Trainer is {{Trainer}} and Duration is {{Duration}}"