- name: Variable from Play level
  hosts: localhost
  vars:
   Course: "DevOps"
   Trainer: "Nivas"
   Duration: "110HRS"
  tasks:
    - name: DebugVariable
      ansible.builtin.debug:
        msg: " Hi I am learning, {{Course}} and Trainer is {{Trainer}} and Duration is {{Duration}} "